version: '3.8'

services:
  app:
    build: .
    ports:
      - "8090:8090"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - ./storage/logs:/var/www/storage/logs
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: hospital_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql_data:
